assets:
  - Virtual Reality Marketplace
  - AI-Powered Investment Hub
  - Blockchain Art Gallery
  - Smart Home Automation Service
  - Renewable Energy Trading Platform

default_asset: Blockchain Art Gallery