assets:
  - 802.1x
  - ABP Payments
  - Amp Proxy
  - Armatron
  - Auto Buying Platform
  - Automated Incentives
  - Automated Testing
  - Battery Pack
  - Billing Engine
  - Build Data Migration
  - Business Intelligence
  - Capsela Backend
  - Capsela DSA Migration
  - Capsela Frontend
  - CCPA
  - Clickstream
  - Consumer Data
  - Consumer Reports
  - Core Payment Engine
  - CorpEng
  - Cypress
  - CZ Migration
  - Data Intelligence
  - Data Science
  - Database Ops
  - Dealer Admin/Management
  - Dealer Portal
  - Dealer Selling Tools
  - Developer Tools
  - DevOps
  - DSA 2.0
  - DSA Migration
  - E-Contracting
  - Enterprise Platform
  - FPT
  - FSBO Capsela Migration
  - GeoData
  - Geode
  - Gluestick
  - Hadoop Image Processor
  - Historical Used Pricing
  - Incentives
  - Incentives Data Manager
  - Lead Router
  - Manual Offers
  - Mobile Geofence
  - Mobile Push Notifications
  - New Curve Data Migration
  - Onboarding Sonic
  - Otto
  - Casper
  - Payment Buttons 2.0
  - Polk Salesmatching
  - Post prospect
  - Price Check
  - Pricing Manager
  - Pricing Tool
  - Pricing Visualization
  - Programmatic Bidding
  - Sales Analyzer
  - SpacePods
  - Sumoforce
  - Tatooine
  - TCDS Infrastructure
  - TCWS Sell/Trade
  - Tealium and Google Analytics
  - Trade
  - Trade Matching
  - Trade Rebuild
  - Trade TCDS
  - Universal Certificate
  - UVD
  - VIPR
  - Marketing Platform
  - XPR
  - Druid Analytical Platform
  - Dealer Comms Mobile App
  - Martech
  - CDP Migration
  - TrueCar Plus
  - Sell Your Car
  - Demand Metrics
  - Checkout Redesign
  - Deal Sheet
  - CDP Upgrade
  - Credit App
  - Machine Learning Platform
  - Astronomer Data Orchestration

default_asset: Auto Buying Platform